# Generated by Django 4.2.7 on 2024-04-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_wallet_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author_level',
            field=models.IntegerField(default=0, verbose_name='Уровень автора'),
        ),
    ]
