# Generated by Django 4.2.7 on 2024-05-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='url_for_payment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
