# Generated by Django 4.2.7 on 2024-05-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_url_for_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='url_for_payment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
