# Generated by Django 4.2.7 on 2024-04-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_comment_author_alter_content_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень подписки'),
        ),
    ]
