# Generated by Django 4.2.7 on 2024-05-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='level',
        ),
        migrations.AddField(
            model_name='content',
            name='subscribers_only',
            field=models.BooleanField(default=False, verbose_name='Только для подписчиков'),
        ),
    ]
